version: '3'
services:
  dependencies:
    build:
      context: .
      dockerfile: dockerfile
    image: base
  scraper:
    build:
      context: ./isat/scraper
      dockerfile: dockerfile
    ports:
      - "8080:8080"
  im-process:
    build:
      context: ./isat/image-process
      dockerfile: dockerfile
    ports:
      - "8081:8080"
