version: '3'
services:
  dependencies:
    build:
      context: .
      dockerfile: Dockerfile
    image: base
  redis:
    image: redis
    ports: 
      - "6379:6379"
  scraper:
    build:
      context: ./isat/scraper
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./isat/data:/isat/data
      - ./images:/app/images
      - ./logs:/app/logs
    depends_on:
      - redis
      - dependencies
  im-process:
    build:
      context: ./isat/imageProcess
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./isat/data:/isat/data
      - ./images:/app/images
      - ./images_empty_bg:/app/images_empty_bg
      - ./logs:/app/logs
    depends_on:
      - dependencies
  color-search:
    build:
      context: ./isat/colorSearch
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./isat/data:/isat/data
      - ./images:/app/images
      - ./images_empty_bg:/app/images_empty_bg
      - ./logs:/app/logs
    depends_on:
      - dependencies
  image-search:
    build:
      context: ./isat/imageSearch
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - ./isat/data:/isat/data
      - ./images:/app/images
      - ./logs:/app/logs
    depends_on:
      - dependencies
